### PR TITLE
add a toggle for sticky header

### PR DESCRIPTION
**Pull request by jason-ojisan**
https://github.com/Ajatt-Tools/rikaitan/commit/09e12f8bb4d91c3bd5e425a08cdc74a95f96aeab#r143854685
@JayXT does it look good?

### CODE REVIEW

**Comment by JayXT** [comment]
@jason-ojisan, I'm not an expert in the Yomitan codebase, but overall the changes in this PR seem logical for me. Although I've noticed that 5 PR checks are failing, so perhaps they have to be addressed.
@tatsumoto-ren, what are your thoughts regarding the proposed changes?

**Comment by jason-ojisan** [comment]
@JayXT just a side note: We stand against the hijack attempt of the (former) Yomichan project by moeway because they promote a flawed and ineffective language learning method which is different from AJATT. Don't say Yomitan. Say **"Rikaitan"** if you also believe the hijack should not succeed.

**Comment by tatsumoto-ren** [comment]
> what are your thoughts regarding the proposed changes?

I think it would be nice to figure out how to update the search page automatically when the toggle is flipped. But it's not a big deal.

**Comment by jason-ojisan** [comment]
@JayXT try running the patched extension to see if that's what you expect.

**Comment by jason-ojisan** [comment]
>Although I've noticed that 5 PR checks are failing, so perhaps they have to be addressed.

The patch should be fine but the tests have to be fixed to work with the updated code. This extension is extremely shitty because it was written by idiots who don't know how to code. And JS/TS is a very bad language by itself. In a perfect world JS would not exist, and everything would be written in C++. But this is not a perfect world.

**Comment by JayXT** [comment]
> @JayXT just a side note: We stand against the hijack attempt of the (former) Yomichan project by moeway because they promote a flawed and ineffective language learning method which is different from AJATT. Don't say Yomitan. Say **"Rikaitan"** if you also believe the hijack should not succeed.

Sorry for the confusion. Yes, I meant Rikaitan, or the original Yomichan. To my understanding the difference in codebase between the two hasn't gotten too wide yet.

**Comment by JayXT** [comment]
> @JayXT try running the patched extension to see if that's what you expect.

Are there any instructions how this can be done?

**Review by tatsumoto-ren — APPROVED** [review]

**Comment by tatsumoto-ren** [comment]
>Are there any instructions how this can be done?

Run [build.sh](https://github.com/Ajatt-Tools/rikaitan/blob/main/build.sh). Then import the file named `rikaitan-firefox-dev.xpi` from the `builds` folder.

**Comment by JayXT** [comment]
FYI, I was able to build and generate rikaitan-firefox-dev.xpi on a VM after solving a couple of issues with missing npm and packages, but importing the custom extension into Firefox is quite an ordeal nowadays:) Changing xpinstall.signatures.required to false is no longer sufficient. Due to time constraints I might look into this later, or since the changes are already merged into main, waiting until the next Rikaitan release is another valid method.

**Comment by tatsumoto-ren** [comment]
@JayXT Running a VM is not necessary at all. To import unsigned extensions you need this version of firefox: [firefox-developer-edition](https://archlinux.org/packages/extra/x86_64/firefox-developer-edition/).

**Comment by JayXT** [comment]
@tatsumoto-ren, yes, you're right  using a VM is optional, but I still prefer to keep my workstation clean and stable always ready for immersion and sentence mining, so for such experiments usually I rely on one of VMs. 

In any case, I was able to install the extension and verify the behavior of the toggle. It seems to be working fine, i.e. when sticky header is turned off, the header gets hidden on scrolling and overflow of header contents is set to visible:

image

image

The only remaining question is that the following CSS is ignored by the header (upper-part has white background), but I guess that will be solved in some different PR:

`body {
    background-color: #fffaf0;
    color: #2a1b0a;
}`

**Comment by tatsumoto-ren** [comment]
Try 
```
:root {
    --background-color: #fffaf0;
    --text-color: #2a1b0a;
}
```

The extension uses variables a lot in the CSS so you can just override them instead of overriding the rules.

**Comment by JayXT** [comment]
That worked out. Thank you!

**Pull request merged**
